[repo]
name = "gyat"
username = "loki"
server = "127.0.0.1:8081"

[ignore]
files = [
    ".gyt/",
    "target/",
    ".git/",
    "gyat-server-data/",
    "server.toml",
]

[ssh]
key_path = "~/.ssh/id_ed25519"
